# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://$(PAT)@github.com/paulwhippey/faddenrecipes
  displayName: 'Git Clone'

- script: ls -l faddenrecipes
  displayName: 'List files'

- script: az storage blob upload-batch --account-name faddenrecipes --auth-mode key --account-key $(KEY) -s "faddenrecipes/" --pattern "!*.yml" -d "\$web/"
  displayName: 'Copy files to Azure storage'
