# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://$(PAT)@github.com/paulwhippey/faddenrecipes
  displayName: 'Git Clone'

- script: ls -l faddenrecipes
  displayName: 'List files'

- script: azcopy copy "faddenrecipes/*.html" "https://faddenrecipes.blob.core.windows.net/$web/$(SAS)"
  displayName: 'Sync files to Azure storage'
